name: ğŸš€ Test Secret & SSH Info

on:
  push:
    branches:
      - dev

jobs:
  test-secret:
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ” Check if secret and SSH info are injected (masked)
        run: |
          echo "ğŸ” SSH key: ${{ secrets.SSH_PRIVATE_KEY }}"
          echo "ğŸ‘¤ SSH user: akhil"
          echo "ğŸŒ SSH server IP: 127.0.0.1"
